export const strapiUrl = process.env['NX_STRAPI_URL']
export const strapiToken = process.env['NX_STRAPI_TOKEN']
export const strapiTokenKey = process.env['NX_STRAPI_TOKEN_KEY']
export const websiteName = process.env['NX_WEBSITE_NAME']
export const tokenKey = process.env['NX_TOKEN_KEY']