name: Create Pull Request Release

on:
  release:
    types: [published]

jobs:
  create:
    name: Create pull request release
    runs-on: ubuntu-latest
    permissions:
      # write permission is required to create a github release
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: add semver
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Set up git
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git fetch
          git checkout main
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor}}@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}"
      - name: Create Pull Request
        uses: actions/github-script@v6
        env:
          TAG_LATEST: ${{ steps.previoustag.outputs.tag }}
        with:
          script: |
            console.log('> TAG_LATEST', process.env.TAG_LATEST)
            const script = require('./scripts/github/createPullRequest.js')
            script({github, exec, context})
