name: Publish
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: "Use NodeJS 16"
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: "Setup NPM" # Interesting step
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor}}@users.noreply.github.com"
        git remote set-url origin "https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}"
        npm ci
    - name: Build package
      run: |
        npm run build
    - name: Version and publish
      uses: actions/github-script@v6
      env:
        TAG_LATEST: ${{ steps.previoustag.outputs.tag }}
      with:
        script: |
          const script = require('./scripts/github/publish.js')
          script({github, exec, context})
