name: Update Pull Request Hotfix

on:
  pull_request:
    types: [labeled]
    branches:
      - main

jobs:
  update:
    name: update pull request hotfix
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'hotfix')
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: "Setup NPM"
        run: |
          npm ci
      - name: Set up git
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git fetch
          branchName=${{ github.head_ref }}
          echo "Branch Name: $branchName"
          git checkout $branchName
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor}}@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}"
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Update Pull Request
        uses: actions/github-script@v6
        env:
          TAG_LATEST: ${{ steps.previoustag.outputs.tag }}
          TAG_LATEST_DATE: ${{ steps.previoustag.outputs.timestamp }}
        with:
          script: |
            const script = require('./scripts/github/updatePullRequestHotfix.js')
            script({github, exec, context})

