name: Update Pull Request Release

on:
  push:
    branches: [develop]

jobs:
  update:
    name: update pull request release
    runs-on: ubuntu-latest
    permissions:
      # write permission is required to create a github release
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the weg Git works, without it this action won't be able to find any or the correct tags
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: "Setup NPM" # Interesting step
        run: |
          npm ci
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Set up git
        run: |
          git fetch
          git checkout develop
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor}}@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}"
      - name: Update Pull Request
        uses: actions/github-script@v6
        env:
          TAG_LATEST: ${{ steps.previoustag.outputs.tag }}
          TAG_LATEST_DATE: ${{ steps.previoustag.outputs.timestamp }}
        with:
          script: |
            const script = require('./scripts/github/updatePullRequest.js')
            script({github, exec, context})

